import { StyleSheet, Platform, StatusBar } from 'react-native';
export const styles = StyleSheet.create({
    //HomeScreen
    container: {
        flex: 1,
        backgroundColor: '#222831', // Fondo oscuro principal
        paddingHorizontal: 12,
        paddingTop: 8,
    },
    tituloPantalla: {
        fontSize: 26,
        fontWeight: 'bold',
        color: '#00adb5', // Turquesa neón
        marginVertical: 16,
        textAlign: 'center',
        letterSpacing: 1.1,
        textShadowColor: '#393e46',
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 6,
    },
    filtrosContainer: {
        backgroundColor: '#393e46',
        borderRadius: 16,
        padding: 14,
        marginBottom: 10,
        marginHorizontal: 0,
        shadowColor: '#00adb5',
        shadowOpacity: 0.09,
        shadowOffset: { width: 0, height: 4 },
        shadowRadius: 10,
        elevation: 4,
    },
    input: {
        backgroundColor: '#222831',
        borderColor: '#00adb5',
        borderWidth: 1.4,
        borderRadius: 12,
        padding: 10,
        fontSize: 16,
        color: '#aaaaaa', // Blanco casi puro
        marginBottom: 3,
        shadowColor: '#00adb5',
        shadowOpacity: 0.04,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 4,
    },
    inputAddPlato: {
        backgroundColor: '#393e46',
        borderColor: '#00adb5',
        borderWidth: 1.4,
        borderRadius: 12,
        padding: 10,
        fontSize: 16,
        color: '#aaaaaa',
        marginBottom: 3,
        shadowColor: '#00adb5',
        shadowOpacity: 0.04,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 4,
    },
    cargando: {
        textAlign: 'center',
        marginTop: 20,
        color: '#00adb5',
        fontWeight: 'bold',
        fontSize: 18,
        letterSpacing: 0.5,
    },
    vacio: {
        textAlign: 'center',
        marginTop: 40,
        color: '#ffb347', // Naranja pastel para mensajes vacíos
        fontWeight: '600',
        fontSize: 17,
    },
    card: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#393e46',
        marginVertical: 9,
        padding: 16,
        borderRadius: 16,
        shadowColor: '#00adb5',
        shadowOpacity: 0.10,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 8,
        elevation: 4,
    },
    imgContainer: {
        width: 68,
        height: 68,
        marginRight: 16,
        borderRadius: 34,
        overflow: 'hidden',
        backgroundColor: '#393e46',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#00adb5',
    },
    img: {
        width: 68,
        height: 68,
        borderRadius: 34,
    },
    imgPlaceholder: {
        justifyContent: 'center',
        alignItems: 'center',
        width: 68,
        height: 68,
    },
    cardContent: {
        flex: 1,
        justifyContent: 'center',
        paddingVertical: 2,
    },
    titulo: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#00adb5',
        marginBottom: 2,
    },
    descripcion: {
        fontSize: 14,
        color: '#eeeeee',
        opacity: 0.92,
        fontWeight: '500',
        marginBottom: 4,
        marginTop: 2,
    },
    fecha: {
        fontSize: 12,
        color: '#ffb347',
        marginTop: 2,
        fontWeight: 'bold',
    },
    button: {
        backgroundColor: '#222831',
        borderRadius: 18,
        paddingHorizontal: 14,
        paddingVertical: 7,
        marginHorizontal: 4,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#00adb5',
        shadowOpacity: 0.12,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 3,
        elevation: 2,
    },
    fab: {
        position: 'absolute',
        bottom: 32,
        right: 32,
        backgroundColor: '#00adb5',
        borderRadius: 32,
        width: 66,
        height: 66,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 8,
        shadowColor: '#00adb5',
        shadowOpacity: 0.20,
        shadowOffset: { width: 0, height: 8 },
        shadowRadius: 14,
    },
    fabTexto: {
        color: '#eeeeee',
        fontSize: 40,
        fontWeight: 'bold',
        lineHeight: 42,
        textShadowColor: '#222831',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 4,
    },
    dropdown: {
        backgroundColor: '#393e46',
        borderColor: '#00adb5',
        borderWidth: 1.5,
        borderRadius: 12,
        minHeight: 44,
        paddingHorizontal: 12,
        zIndex: 2000,
    },
    dropdownContainer: {
        backgroundColor: '#393e46',
        borderColor: '#00adb5',
        borderWidth: 1.5,
        borderRadius: 12,
        zIndex: 2500,
        // sombras solo si querés, para overlay
        shadowColor: '#00adb5',
        shadowOpacity: 0.10,
        shadowOffset: { width: 0, height: 3 },
        shadowRadius: 7,
        elevation: 7,

    },
    dropdownPlaceholder: {
        color: '#aaaaaa',
        fontSize: 15,
        marginLeft: 4,
    },
    dropdownLabel: {
        color: '#eeeeee',
        fontSize: 15,
        fontWeight: '500',
    },
    dropdownSelectedLabel: {
        color: '#00adb5',
        fontWeight: 'bold',
        fontSize: 16,
    },
    dropdownListItem: {
        borderBottomColor: '#25272A',
        borderBottomWidth: 0.6,
        backgroundColor: '#393e46',
    },
    dropdownArrow: {
        tintColor: '#00adb5',
    },
    //AddPlato
    fotoContainer: {
        alignSelf: 'center',
        width: 128,
        height: 128,
        borderRadius: 16,
        backgroundColor: '#393e46',
        justifyContent: 'center',
        alignItems: 'center',
        marginVertical: 14,
        overflow: 'hidden',
        shadowColor: "#00adb5",
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.18,
        shadowRadius: 8,
        elevation: 8,
    },
    foto: {
        width: 128,
        height: 128,
        borderRadius: 16,
    },
    loadingOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: '#393e4688',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 9999,
    },
    row: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 10,
        marginBottom: 8,
        marginHorizontal: 0,
    },
    favoritoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 16,
        alignSelf: 'center',
    },
    ubicacionStack: {
        alignItems: 'center',
        marginBottom: 16,
    },
    favoritoLabel: {
        marginRight: 8,
        fontSize: 16,
        color: '#00adb5',
        fontWeight: 'bold',
    },
    ubicacionRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 12,
        alignSelf: 'center',
    },
    ubicacionText: {
        marginLeft: 12,
        color: '#eeeeee',
        fontSize: 14,
        fontWeight: '600',
        textAlign: 'center',
    },
    exitoBg: {
        flex: 1,
        backgroundColor: '#222831cc',
        justifyContent: 'center',
        alignItems: 'center',
    },
    exitoCard: {
        backgroundColor: '#393e46',
        padding: 32,
        borderRadius: 18,
        alignItems: 'center',
        minWidth: 260,
        shadowColor: "#00adb5",
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.18,
        shadowRadius: 18,
        elevation: 14,
    },
    exitoTitulo: {
        fontSize: 23,
        fontWeight: 'bold',
        marginBottom: 10,
        color: '#00adb5',
        letterSpacing: 0.2,
    },
    exitoTexto: {
        fontSize: 17,
        marginBottom: 22,
        color: '#eeeeee',
        textAlign: 'center',
        fontWeight: '500',
    },
    accionesRow: {
        flexDirection: 'row',
        gap: 16,
        marginTop: 24,
        justifyContent: 'center',
    },
    fotoModalBg: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.95)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    fotoModalContainer: {
        width: '96%',
        height: '80%',
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative',
    },
    cerrarX: {
        position: 'absolute',
        top: 0,
        right: 0,
        zIndex: 2,
        padding: 12,
    },
    fotoAmpliada: {
        width: '100%',
        height: '100%',
        borderRadius: 22,
    },
    botonPrimario: {
        backgroundColor: '#00adb5',
        paddingVertical: 13,
        paddingHorizontal: 26,
        borderRadius: 26,
        marginHorizontal: 8,
        alignItems: 'center',
        shadowColor: '#00adb5',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.17,
        shadowRadius: 8,
        elevation: 5,
    }, botonPrimarioDisabled: {
        backgroundColor: '#aaaa',
        paddingVertical: 13,
        paddingHorizontal: 26,
        borderRadius: 26,
        marginHorizontal: 8,
        alignItems: 'center',
        shadowColor: '#00adb5',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.17,
        shadowRadius: 8,
        elevation: 5,
    },
    botonPrimarioText: {
        color: '#eeeeee',
        fontWeight: 'bold',
        fontSize: 17,
        letterSpacing: 1.2,
    },
    botonSecundario: {
        backgroundColor: '#c00',
        paddingVertical: 13,
        paddingHorizontal: 22,
        borderRadius: 26,
        marginHorizontal: 8,
        alignItems: 'center',
        shadowColor: '#c00',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.13,
        shadowRadius: 7,
        elevation: 3,
    },
    botonSecundarioText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 17,
        letterSpacing: 1,
    },
    botonFoto: {
        backgroundColor: '#7fd1b9',
        paddingVertical: 12,
        paddingHorizontal: 22,
        borderRadius: 22,
        marginHorizontal: 6,
        marginBottom: 4,
        alignItems: 'center',
        shadowColor: '#00adb5',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.11,
        shadowRadius: 6,
        elevation: 3,
    },
    botonFotoText: {
        color: '#222831',
        fontWeight: 'bold',
        fontSize: 16,
    },
    botonGaleria: {
        backgroundColor: '#ad7df6',
        paddingVertical: 12,
        paddingHorizontal: 22,
        borderRadius: 22,
        marginHorizontal: 6,
        marginBottom: 4,
        alignItems: 'center',
        shadowColor: '#ad7df6',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.11,
        shadowRadius: 6,
        elevation: 3,
    },
    botonGaleriaText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
    },
    botonUbicacion: {
        backgroundColor: '#ffb347',
        paddingVertical: 12,
        paddingHorizontal: 22,
        borderRadius: 22,
        marginHorizontal: 6,
        alignItems: 'center',
        shadowColor: '#ffb347',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.12,
        shadowRadius: 7,
        elevation: 3,
    },
    botonUbicacionDeshabilitado: {
        backgroundColor: '#D4963F',
        paddingVertical: 12,
        paddingHorizontal: 22,
        borderRadius: 22,
        marginHorizontal: 6,
        alignItems: 'center',
        shadowColor: '#ffb347',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.12,
        shadowRadius: 7,
        elevation: 3,
    },
    botonUbicacionText: {
        color: '#222831',
        fontWeight: 'bold',
        fontSize: 16,
    },
    botonUbicacionTextDehabilitado: {
        color: '#222831',
        fontWeight: 'bold',
        fontSize: 16,
    },
    //EditPlato
    mapaContainer: {
        width: 250,
        height: 250,
        borderRadius: 250,
        backgroundColor: '#393e46',
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
        marginBottom: 8,
    },
    subtitulo: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#00adb5',
        marginTop: 24,
        marginBottom: 8,
        textAlign: 'center',
    },
    hora: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#ffb347',
        marginTop: 24,
        marginBottom: 8,
        textAlign: 'center',
    },
    image: {
        width: '100%',
        height: '100%',
        borderRadius: 250,
    },
    botonCancelar: {
        backgroundColor: '#393e46',
        paddingVertical: 13,
        paddingHorizontal: 18,
        borderRadius: 26,
        marginHorizontal: 4,
        alignItems: 'center',
        shadowColor: '#333',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.09,
        shadowRadius: 5,
        elevation: 2,
        flex: 1,
    },
    botonCancelarModal: {
        backgroundColor: '#eeeeee',
        paddingVertical: 13,
        paddingHorizontal: 18,
        borderRadius: 26,
        marginHorizontal: 4,
        alignItems: 'center',
        shadowColor: '#333',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.09,
        shadowRadius: 5,
        elevation: 2,
        flex: 1,
    },
    botonCancelarText: {
        color: '#eeeeee',
        fontWeight: 'bold',
        fontSize: 15,
        letterSpacing: 0.5,
    },
    botonOK: {
        backgroundColor: '#00adb5', // Turquesa neón (primario)
        paddingVertical: 13,
        paddingHorizontal: 30,
        borderRadius: 26,
        alignItems: 'center',
        marginTop: 10,
        shadowColor: '#00adb5',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.17,
        shadowRadius: 8,
        elevation: 5,
    },
    botonOKText: {
        color: '#eeeeee',
        fontWeight: 'bold',
        fontSize: 17,
        letterSpacing: 1.2,
    },
    botonCancelarTextModal: {
        color: '#aaaaa',
        fontWeight: 'bold',
        fontSize: 15,
        letterSpacing: 0.5,
    },
    botonEliminar: {
        backgroundColor: '#c00',
        paddingVertical: 13,
        paddingHorizontal: 18,
        borderRadius: 26,
        marginHorizontal: 4,
        alignItems: 'center',
        shadowColor: '#c00',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.12,
        shadowRadius: 7,
        elevation: 3,
        flex: 1,
    },
    botonEliminarText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 15,
        //letterSpacing: 0.5,
    },
    botonGuardar: {
        backgroundColor: '#00adb5',
        paddingVertical: 13,
        paddingHorizontal: 18,
        borderRadius: 26,
        marginHorizontal: 4,
        alignItems: 'center',
        shadowColor: '#00adb5',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.17,
        shadowRadius: 8,
        elevation: 5,
        flex: 1,
    },
    botonGuardarText: {
        color: '#eeeeee',
        fontWeight: 'bold',
        fontSize: 15,
        letterSpacing: 1.2,
    },
    accionesRowEditarPlato: {
        flexDirection: 'row',
        gap: 10,
        justifyContent: 'space-between',
        marginBottom: 10,
        marginTop: 16,
    },
    //MapScreen
    imageContainer: {
        flex: 1,
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 12,
        marginBottom: 6,
        borderRadius: 24,
        overflow: 'hidden',
        backgroundColor: '#393e46',
        shadowColor: '#00adb5',
        shadowOpacity: 0.15,
        shadowOffset: { width: 0, height: 3 },
        shadowRadius: 9,
        elevation: 5,
    },
    imagen: {
        width: '100%',
        height: '100%',
        borderRadius: 24,
        resizeMode: 'cover',
    },
    buttonText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 14,
        letterSpacing: 0.6,
    },
    //StatsScreen
    containerStats: {
        alignItems: 'center',
        flex: 1,
        paddingVertical: 18,
        backgroundColor: '#222831', // Dark mode fondo
        minHeight: '100%',
        paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,

    },
    title: {
        fontSize: 27,
        fontWeight: 'bold',
        color: '#00adb5',
        marginBottom: 20,
        textAlign: 'center',
        letterSpacing: 0.5,
        marginTop: 8,
        textShadowColor: '#393e46',
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 7,
    },
    box: {
        backgroundColor: '#393e46',
        borderRadius: 16,
        padding: 20,
        marginBottom: 16,
        alignItems: 'center',
        width: '92%',
        shadowColor: "#00adb5",
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.07,
        shadowRadius: 7,
        elevation: 3,
    },
    subtitle: {
        fontSize: 17,
        color: '#eeeeee',
        fontWeight: '600',
        marginBottom: 8,
        textAlign: 'center',
    },
    total: {
        fontSize: 39,
        fontWeight: 'bold',
        color: '#00adb5',
        marginBottom: 2,
    },
    promedio: {
        fontSize: 32,
        color: '#ffb347',
        fontWeight: 'bold',
        marginBottom: 2,
    },
    favorito: {
        fontSize: 16,
        color: '#00adb5',
        fontWeight: '600',
        marginBottom: 2,
    },
    scrollContentStats: {
        alignItems: 'center',
        paddingVertical: 18,
        paddingBottom: 50,
    },
    //ProfileScreen
    botonCerrarSesion: {
        flex: 1,
        backgroundColor: '#393e46',
        paddingVertical: 13,
        borderRadius: 26,
        alignItems: 'center',
        shadowColor: '#393e46',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.11,
        shadowRadius: 6,
        elevation: 3,
        marginHorizontal: 2,
        borderWidth: 1,
        borderColor: '#00adb5'
    },
    botonCerrarSesionText: {
        color: '#ffb347',
        fontWeight: 'bold',
        fontSize: 17,
        letterSpacing: 1.2,
    },
    //LoginScreen
    containerLogin: {
        flex: 1,
        backgroundColor: '#222831',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 22,
    },
    imageLogin: {
        width: 140,
        height: 140,
        marginBottom: 8,
    },
    titleLogin: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#00adb5', 
        marginBottom: 20,     // <-- SOLO abajo, no arriba
        textAlign: 'center',
        letterSpacing: 1,
        textShadowColor: '#393e46',
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 6,
    },
    inputLogin: {
        backgroundColor: '#393e46',
        borderColor: '#00adb5',
        borderWidth: 1.4,
        borderRadius: 12,
        padding: 14,
        fontSize: 16,
        color: '#eeeeee',
        marginBottom: 16,
        width: 260,
        shadowColor: '#00adb5',
        shadowOpacity: 0.08,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 4,
    },
    botonLogin: {
        backgroundColor: '#00adb5',
        borderRadius: 26,
        paddingVertical: 13,
        alignItems: 'center',
        marginTop: 6,
        marginBottom: 4,
        width: 260,         // Igual que input
        shadowColor: '#00adb5',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.13,
        shadowRadius: 7,
        elevation: 4,
    },
    botonLoginText: {
        color: '#eeeeee',
        fontWeight: 'bold',
        fontSize: 18,
        letterSpacing: 1.1,
    },
    error: {
        color: '#c00',
        marginTop: 12,
        fontWeight: 'bold',
        textAlign: 'center',
        fontSize: 15,
    },
    linkRegistrarse: {
        marginTop: 22,
        textAlign: 'center',
        color: '#00adb5',
        fontSize: 16,
        fontWeight: 'bold',
        textDecorationLine: 'underline',
        letterSpacing: 0.3,
    },
    //RegisterScreen
    botonRegistro: {
        backgroundColor: '#00adb5',
        borderRadius: 26,
        paddingVertical: 13,
        alignItems: 'center',
        marginTop: 6,
        width: 260,
        shadowColor: '#00adb5',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.13,
        shadowRadius: 7,
        elevation: 4,
    },
    botonRegistroText: {
        color: '#eeeeee',
        fontWeight: 'bold',
        fontSize: 18,
        letterSpacing: 1.1,

    },
    containerRegister: {
        flex: 1,
        backgroundColor: '#222831',
        //justifyContent: 'center',
        alignItems: 'center', // ← centra horizontal
        padding: 22,
    },
    inputRegister: {
        backgroundColor: '#393e46',
        borderColor: '#00adb5',
        borderWidth: 1.4,
        borderRadius: 12,
        padding: 14,
        fontSize: 16,
        color: '#eeeeee',
        marginBottom: 16,
        width: 260,         // ANCHO FIJO para inputs, así quedan centrados
        shadowColor: '#00adb5',
        shadowOpacity: 0.08,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 4,
    }
});

